### ISSUE TITLE
Login system 테스트 요청

### ISSUE THREAD

**Issue by KoharuDaisukii** [Samcheon/StudytimeCheck#10]
USER_INFO_DIR "users"
USER_INFO_FILE "user_info.txt"

유저 정보가 담긴 디렉토리는 임시로 users로 정했음.
실행 파일이랑 같은 폴더에 "users" 폴더를 만들고 그 폴더 안에 "user_info.txt" 파일도 만들어서 함 실행해봐주면 감사함.

$ ./StudytimeCheck UID
위 커맨드 입력했을 때 정상 작동 시 ID가 존재하지 않는다면서 가입하라고 할 거임.

**Comment by Elisha0510** [comment]
Git command에 명령어 입력하는거지 ?

**Comment by Elisha0510** [comment]
웅 해볼게. 근데 나만 코드 우분투에 복사하면 이상하게 복사되나 ?
하나하나 입력해야할듯...

**Comment by Elisha0510** [comment]
![image](https://user-images.githubusercontent.com/82575174/235757057-701afca6-3e0c-44f1-9d42-4f77b5ed4296.png)
지금 실행파일 StudyTimeCheck.c 가 있는 파일에 user_info를 만들고 했는데 그런 디렉토리가 없다고 하네

**Comment by KoharuDaisukii** [comment]
미안 코드 수정하면서 디렉토리 이름 바꿨는데 까먹었네 본문도 수정하겠음

**Comment by Elisha0510** [comment]
오오 users 폴더에 user_info.txt 넣으니까 실행된다 ! 근데 진짜 우리 메뉴 UI는 예쁘게 어떻게 해봐야겠다 ㅋㅋㅋㅋㅋㅋ
